version: "3"
services:
    homeassistant:
        image: homeassistant/raspberrypi4-homeassistant:stable
        restart: unless-stopped
        volumes:
            - ./config/homeassistant:/config
        devices:
            - ${ZIGBEE_DEVICE}:/dev/ttyAMA0
        environment:
            - TZ=America/New_York
        depends_on:
            - swag
            - mqtt
            - zwavejs2mqtt
            - zigbee2mqtt

    zwavejs2mqtt:
        container_name: zwavejs2mqtt
        image: zwavejs/zwavejs2mqtt:latest
        restart: always
        tty: true
        stop_signal: SIGINT
        environment:
            - SESSION_SECRET=${ZWAVEJS_SECRET}
            - TZ=America/New_York
            - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
        devices:
            # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
            # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
            - "${ZWAVE_DEVICE}:/dev/zwave"
        volumes:
            - ./store:/usr/src/app/store
        ports:
            - "8091:8091" # port for web interface
            - "3000:3000" # port for Z-Wave JS websocket server
        depends_on:
            - mqtt

    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: koenkk/zigbee2mqtt
        restart: unless-stopped
        volumes:
            - ./config/zigbee:/app/data
            - /run/udev:/run/udev:ro
        ports:
            # Frontend port
            - 8092:8080
        environment:
            - TZ=America/Toronto
        devices:
            # Make sure this matched your adapter location
            - ${ZIGBEE_DEVICE}:/dev/zigbee
        depends_on:
            - mqtt

    mqtt:
        image: eclipse-mosquitto
        restart: unless-stopped
        environment:
            - TZ=America/New_York
        volumes:
            - ./config/mqtt:/mosquitto/config/
        ports:
            - "1883:1883"
            - "9001:9001"

    # deconz:
    #     image: deconzcommunity/deconz:stable
    #     restart: unless-stopped
    #     volumes:
    #         - ./config/deconz:/opt/deCONZ
    #     devices:
    #         - ${ZIGBEE_DEVICE}:/dev/ttyAMA0
    #     environment:
    #         - DECONZ_WEB_PORT=801
    #         - DECONZ_WS_PORT=445
    #         - DECONZ_VNC_MODE=1
    #         - DECONZ_VNC_PORT=5930
    #         - DECONZ_VNC_PASSWORD=${DECONZ_VNC_PASSWORD}
    #         - DEBUG_INFO=1
    #         - DECONZ_UPNP=0
    #         - TZ=America/New_York
    #     ports:
    #         - "801:801"
    #         - "445:445"
    #         - "5930:5930"

    duckdns:
        image: linuxserver/duckdns:arm32v7-latest
        restart: unless-stopped
        environment:
            - TZ=America/New_York
            - SUBDOMAINS=${DUCKDNS_SUBDOMAIN}
            - TOKEN=${DUCKDNS_TOKEN}
            - LOG_FILE=false #optional

    swag:
        image: linuxserver/swag:arm32v7-latest
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./config/swag:/config
        environment:
            - PGID=1001
            - PUID=1001
            - EMAIL=${LETSENCRYPT_EMAIL}
            - URL=${DUCKDNS_SUBDOMAIN}.duckdns.org
            - VALIDATION=duckdns
            - DUCKDNSTOKEN=${DUCKDNS_TOKEN}
            - SUBDOMAINS=wildcard
            - TZ=America/New_York
        ports:
            - "443:443"
            - "80:80"
        depends_on:
            - duckdns
networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.0.0/12
