FROM alpine/git:latest

ARG REPO
ARG SSH_PRIVATE_KEY

RUN mkdir ~/.ssh/
RUN echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
RUN chmod 600 ~/.ssh/id_rsa
RUN ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN export GIT_SSH_COMMAND='ssh -i /root/.ssh/id_rsa -o "StrictHostKeyChecking=no"'
RUN git clone ${REPO} /git

# CMD ["git", "version"]
