version: '3'
services:
  homeassistant:
    image: homeassistant/raspberrypi4-homeassistant:stable
    restart: unless-stopped
    volumes:
      - ./volumes/homeassistant:/config
    devices:
      - /dev/conbee
    environment:
      - TZ=America/New_York
    depends_on:
      - swag
      - deconz
      - mqtt
      - zwavejs2mqtt
  
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=supersecret
      - TZ=America/New_York
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - /dev/zstick
    volumes:
      - ./store:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server

  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    volumes:
      - ./volumes/mosquitto/config:/mosquitto/config
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  deconz:
    image: deconzcommunity/deconz:stable
    restart: unless-stopped
    volumes:
      - ./volumes/deconz:/opt/deCONZ
    devices:
      - /dev/conbee:/dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=801
      - DECONZ_WS_PORT=445
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5930
      - DECONZ_VNC_PASSWORD=supersecret
      - DEBUG_INFO=1
      - DECONZ_UPNP=0
      - TZ=America/New_York
    ports:
      - "801:801"
      - "445:445"
      - "5930:5930"

  swag:
    image: linuxserver/swag:arm32v7-latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/swag:/config
    environment:
      - PGID=1001
      - PUID=1001
      - EMAIL=francois@francoiscote.net
      - URL=ha.francoiscote.net
      - VALIDATION=dns
      - DNSPLUGIN=digitalocean
      - TZ=America/New_York
    ports:
      - "443:443"
      - "80:80"

volumes:
  zwave-config:
