- platform: mjpeg
  mjpeg_url: http://motion-1.local:8081
  name: camera1
  username: panet
  password: !secret camera1_password
  verify_ssl: false
- platform: mjpeg
  mjpeg_url: http://motion-2.local:8081
  name: camera2
  username: panet
  password: !secret camera2_password
  verify_ssl: false
