sensor.et_wv525_kib_s_received:
  friendly_name: "Données reçues par le routeur"
sensor.et_wv525_kib_s_sent:
  friendly_name: "Données envoyées par le routeur"
sensor.et_wv525_external_ip:
  friendly_name: "IP Externe"
binary_sensor.et_wv525_wan_status:
  friendly_name: "Internet"

camera.camera1:
  friendly_name: "Caméra 1"
camera.camera2:
  friendly_name: "Caméra 2"

climate.thermostat_salon:
  friendly_name: "Thermostat"
sensor.thermostat_salon_temperature:
  friendly_name: "Température (Thermostat)"

climate.thermostat_salle_de_bain:
  friendly_name: "Thermostat"
sensor.thermostat_salle_de_bain_temperature:
  friendly_name: "Température (Thermostat)"

climate.thermostat_chambre:
  friendly_name: "Thermostat"
sensor.thermostat_chambre_temperature:
  friendly_name: "Température (Thermostat)"

climate.thermostat_salle_de_bain_2:
  friendly_name: "Thermostat"
sensor.thermostat_salle_de_bain_2_temperature:
  friendly_name: "Température (Thermostat)"

climate.thermostat_vestibule_2:
  friendly_name: "Thermostat"
sensor.thermostat_vestibule_2_temperature:
  friendly_name: "Température (Thermostat)"

climate.thermostat_sous_sol_centre:
  friendly_name: "Thermostat"
sensor.thermostat_sous_sol_centre_temperature:
  friendly_name: "Température (Thermostat)"

climate.thermostat_sous_sol_fenetre:
  friendly_name: "Thermostat"
sensor.thermostat_sous_sol_fenetre_temperature:
  friendly_name: "Température (Thermostat)"

sensor.capteur_salon_temperature:
  friendly_name: "Température"
sensor.capteur_salon_humidity:
  friendly_name: "Humidité"
sensor.capteur_salon_illuminance:
  friendly_name: "Luminosité"
sensor.capteur_salon_ultraviolet:
  friendly_name: "UV"
sensor.capteur_salon_battery_level:
  friendly_name: "Niveau de la batterie"
binary_sensor.capteur_salon_low_battery_level:
  friendly_name: "Batterie faible"
binary_sensor.capteur_salon_motion:
  friendly_name: "Mouvement"

sensor.capteur_vestibule_2_temperature:
  friendly_name: "Température"
sensor.capteur_vestibule_2_humidity:
  friendly_name: "Humidité"
sensor.capteur_vestibule_2_illuminance:
  friendly_name: "Luminosité"
sensor.capteur_vestibule_2_battery_level:
  friendly_name: "Niveau de la batterie"
binary_sensor.capteur_vestibule_2_low_battery_level:
  friendly_name: "Batterie faible"
binary_sensor.capteur_vestibule_2_motion:
  friendly_name: "Mouvement"

sensor.capteur_sous_sol_temperature:
  friendly_name: "Température"
sensor.capteur_sous_sol_humidity:
  friendly_name: "Humidité"
sensor.capteur_sous_sol_illuminance:
  friendly_name: "Luminosité"
sensor.capteur_sous_sol_ultraviolet:
  friendly_name: "UV"
sensor.capteur_sous_sol_battery_level:
  friendly_name: "Niveau de la batterie"
binary_sensor.capteur_sous_sol_low_battery_level:
  friendly_name: "Batterie faible"
binary_sensor.capteur_sous_sol_motion:
  friendly_name: "Mouvement"
