- name: "Home Assistant"
  port: 21063
  filter:
      include_entities:
          - climate.thermostat_salon
          - sensor.thermostat_salon_temperature
          - climate.thermostat_salle_de_bain
          - sensor.thermostat_salle_de_bain_temperature
          - climate.thermostat_chambre
          - sensor.thermostat_chambre_temperature
          - climate.thermostat_salle_de_bain_2
          - sensor.thermostat_salle_de_bain_2_temperature
          - climate.thermostat_vestibule_2
          - sensor.thermostat_vestibule_2_temperature
          - sensor.capteur_salon_temperature
          - sensor.capteur_salon_humidity
          - sensor.capteur_salon_illuminance
          - binary_sensor.capteur_salon_motion
- name: "Camera 1"
  mode: accessory
  port: 21064
  filter:
      include_entities:
          - camera.camera1
- name: "Camera 2"
  mode: accessory
  port: 21065
  filter:
      include_entities:
          - camera.camera2
