# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  external_url: https://ha.francoiscote.net

  customize:
    light.divan_duo:
      icon: mdi:ceiling-light-multiple
    light.play_lights_duo:
      icon: mdi:monitor-multiple
    light.escalier:
      icon: mdi:stairs

# HTTP Proxy
# -----------------------
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.23.0.0/16

discovery:
  ignore:
    - google_cast

# MQTT
# -----------------------
mqtt:
  broker: mqtt

# Wemo
# -----------------------
wemo:
  discovery: false
  static:
    - 192.168.86.57

# InfluxDB (for Grafana)
# -----------------------
influxdb:
  host: grafana.francoiscote.net
  database: homeassistant

# GOOGLE ASSISTANT
# -----------------------
google_assistant:
  project_id: homeassistant-93748
  service_account: !include google_service_account.json
  report_state: true
  exposed_domains:
    - scene
    - switch
    - light
    - climate
    - sensor
  entity_config:
    light.bureau:
      expose: false
    light.salon:
      expose: false
    light.chambre_louis:
      expose: false
    light.chambre_principale:
      expose: false
    light.exterieur:
      expose: false

# TEXT TO SPEECH
# -----------------------
tts:
  - platform: google_translate

# LOGGER
# -----------------------
logger: 
  default: info
    
# FRONT-END
# -----------------------
frontend:
  themes: !include_dir_merge_named themes
lovelace:
  mode: yaml

# INCLUDES
# -----------------------
light: !include lights.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
