title: 620 Ball
views:
  - title: Lights
    path: lights
    icon: "mdi:lightbulb-on"
    badges: []
    cards:
      - title: Chambre à coucher
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.lit
      - title: Chambre Louis
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.table_a_langer
          - entity: light.table_a_langer
            type: "custom:rgb-light-card"
            justify: center
            colors:
              - rgb_color:
                  - 255
                  - 129
                  - 1
                brightness: 45
                icon_color: "linear-gradient(#c7770d, #732607)"
          - entity: light.table_a_langer
            type: "custom:rgb-light-card"
            justify: center
            colors:
              - rgb_color:
                  - 255
                  - 0
                  - 0
                brightness: 160
                icon_color: "red"
              - rgb_color:
                  - 255
                  - 130
                  - 0
                brightness: 180
                icon_color: "orange"
              - rgb_color:
                  - 255
                  - 230
                  - 0
                brightness: 200
                icon_color: "yellow"
              - rgb_color:
                  - 120
                  - 255
                  - 0
                brightness: 200
                icon_color: "lightgreen"
              - rgb_color:
                  - 0
                  - 255
                  - 190
                brightness: 200
                icon_color: "turquoise"
              - rgb_color:
                  - 60
                  - 126
                  - 255
                brightness: 200
                icon_color: "blue"
              - rgb_color:
                  - 126
                  - 16
                  - 255
                brightness: 200
                icon_color: "purple"
              - rgb_color:
                  - 255
                  - 110
                  - 255
                brightness: 140
                icon_color: "pink"
          - entity: light.lecture
          - entity: light.plafond_chambre_louis
          - type: "custom:rgb-light-card"
            justify: center
            colors:
              - type: call-service
                service: scene.turn_on
                service_data:
                  entity_id: scene.louis_standard
                icon_color: "linear-gradient(135deg, #fdfcfb, #e2d1c3)"
              - type: call-service
                service: scene.turn_on
                service_data:
                  entity_id: scene.louis_dodo
                icon_color: "linear-gradient(135deg, #fee140, #fa709a)"
      - title: Séjour
        entities:
          - entity: light.divan_duo
          - entity: light.panthella
          - entity: light.table
          - entity: light.etagere
        type: entities
        show_header_toggle: false
      - title: Bureau
        entities:
          - type: "custom:fold-entity-row"
            head: light.play_lights_duo
            entities:
              - entity: light.play_light_left
                name: Left
              - entity: light.play_light_right
                name: Right
          - type: "custom:rgb-light-card"
            justify: center
            colors:
              - type: call-service
                service: scene.turn_on
                service_data:
                  entity_id: scene.bureau_travail
                icon_color: "linear-gradient(135deg, #fdfcfb, #e2d1c3)"
              - type: call-service
                service: scene.turn_on
                service_data:
                  entity_id: scene.bureau_geek_night
                icon_color: "linear-gradient(135deg, #ddd6f3, #faaca8)"
              - type: call-service
                service: scene.turn_on
                service_data:
                  entity_id: scene.bureau_ultra_geek
                icon_color: "linear-gradient(135deg, #817bed, #f58f51)"
              - type: call-service
                service: scene.turn_on
                service_data:
                  entity_id: scene.bureau_warm_night
                icon_color: "linear-gradient(135deg, #fee140, #fa709a)"
              - type: call-service
                service: scene.turn_on
                service_data:
                  entity_id: scene.bureau_stream
                icon_color: "linear-gradient(135deg, #b3d5ff, #ffd582)"

        type: entities
      - title: Sous-Sol
        type: entities
        entities:
          - entity: light.escalier
          - entity: light.salle_de_jeu
          - entity: switch.neons_salle_de_lavage
      - title: Extérieur
        type: entities
        show_header_toggle: false
        entities:
          - entity: light.balcon_arriere
      - title: Scènes
        type: horizontal-stack
        cards:
          - entity: script.1586208826829
            hold_action:
              action: more-info
            icon: "mdi:brightness-2"
            icon_height: 50px
            name: "Off"
            show_icon: true
            show_name: true
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.turn_off_all
            type: entity-button
          - entity: scene.matin
            hold_action:
              action: more-info
            icon: "mdi:brightness-6"
            icon_height: 50px
            show_icon: true
            show_name: true
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.matin
            type: entity-button
          - entity: scene.partout_sunset_present
            hold_action:
              action: more-info
            icon: "mdi:brightness-5"
            icon_height: 50px
            name: "On"
            show_icon: true
            show_name: true
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.partout_sunset_present
            type: entity-button
  - title: Temperature
    path: home
    panel: false
    icon: mdi:thermometer
    cards:
      - type: weather-forecast
        entity: weather.thermostat
      - type: thermostat
        entity: climate.thermostat
      - type: custom:mini-graph-card
        name: Ecobee Sensors
        points_per_hour: 2
        show: 
          points: false
        entities:
          - entity: sensor.thermostat_temperature
            name: Thermostat
          - entity: sensor.emilie_temperature
            name: Émilie
          - entity: sensor.living_room_temperature
            name: Salon
          - entity: sensor.multi_sensor
            name: Chambre Louis
      - type: custom:mini-graph-card
        entities: 
          - sensor.aquara_biere
  - title: PiServer
    path: piserver
    icon: "mdi:server-network"
    cards:
      - title: Updates
        type: glance
        show_name: true
        entities:
          - name: HA Update
            entity: binary_sensor.updater
          - name: HACS
            entity: sensor.hacs
            
      - title: Batteries
        type: glance
        show_name: true
        entities:
          - name: Aquara Chambre Louis
            entity: sensor.multi_sensor_battery_level
          - name: Aquara Bière
            entity: sensor.aquara_biere_battery_level
          - name: Remote Tradfri Chambre 
            entity: sensor.tradfri_remote_control_battery_level
